### ISSUE TITLE
install.py fails if Python3 alias is not available

### ISSUE THREAD

**Issue by keon94** [devchat-ai/devchat-vscode#178]
If the python3 alias is not available, [this](https://github.com/covespace/devchat-vscode/blob/857f73a4d92bbef663bf1fedce07bbbada68d8ca/tools/install.py#L15) is obviously going to fail. I encountered this on Windows where we only get python.exe by default.

Solution:
Either handle this case in the script and fall back to looking for "python" in the env if "python3" is unavailable, or add some docs to the readme telling the user that "python3" needs to be available.

**Comment by yangbobo2021** [comment]
Closed in v0.1.10
