### ISSUE TITLE
[Question] Prompt in instruct.txt not same with prompt directly write in command input

### ISSUE THREAD

**Issue by narrowizard** [devchat-ai/devchat-vscode#65]
When I save the prompt to instruct.txt and using the pre-defined command, it replied very differently to the case when I directly write the prompt in the input box. Any hidden logic in the backend?  
## For example
- My prompt: Please write a semantic commit message. Related jira issue is EE-13660

### response when using pre-defined command.
![image](https://github.com/covespace/devchat-vscode/assets/11383928/17660737-e9ff-441c-ab3f-9554b3c0cda7)

### response when directly writing the prompt in input box
![image](https://github.com/covespace/devchat-vscode/assets/11383928/2f11e629-8b7d-471d-9f00-0868cdc44b73)

The second response is a little related while the first one seems totally not related to my diff.  
> The two tests are with the same git diff, with a new jest test file.

**Comment by basicthinker** [comment]
I think the difference comes from the more information you provided (although it is just an issue ID). Also, if the two messages were sent consecutively, GPT already knows the rules in instruct.txt when replying to the second message. If you don't give instruct.txt at all, GPT doesn't necessarily follow the length of title and body lines.

**Comment by narrowizard** [comment]
>  Also, if the two messages were sent consecutively, GPT already knows the rules in instruct.txt when replying to the second message.

Seems it kept context when I ask for GPT multi times. If so, how can I start a new conversation? we need this feature.  

> (although it is just an issue ID)

I have updated the `.chat/workflows/commit_message/instruct.txt` file as `Please write a semantic commit message. Related jira issue is EE-13660` (including the jira issue id, just for test case). Maybe I was lack of some steps to update the instruct.txt ?

**Comment by yangbobo2021** [comment]
"how can I start a new conversation? we need this feature" this feature has in v0.1.6
